// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vulicy.DB;

#nullable disable

namespace Vulicy.DB.Migrations
{
    [DbContext(typeof(VulicyDbContext))]
    [Migration("20260206005512_JsonBDossierFields")]
    partial class JsonBDossierFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("DossierRecordEntitySequence");

            modelBuilder.HasSequence("FeatureEntitySequence");

            modelBuilder.Entity("Vulicy.Domain.CadastreFeatureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Ate")
                        .HasColumnType("integer");

                    b.Property<string>("AteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AteNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryNameShort")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CategoryNameShortBel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("District")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DistrictNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ElementNameBel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer");

                    b.Property<string>("ElementTypeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementTypeNameBel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementTypeShortName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ElementTypeShortNameBel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<int>("IdIae")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ObjectNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ParentAte")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("RegionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegionNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("VillageCouncil")
                        .HasColumnType("integer");

                    b.Property<string>("VillageCouncilName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VillageCouncilNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId")
                        .IsUnique();

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("CadastreFeature", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Vulicy.Domain.CadastreFeatureHistoricEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ChangeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ate")
                        .HasColumnType("integer");

                    b.Property<string>("AteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AteNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryNameShort")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CategoryNameShortBel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("District")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DistrictNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ElementNameBel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer");

                    b.Property<string>("ElementTypeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementTypeNameBel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementTypeShortName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ElementTypeShortNameBel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<int>("IdIae")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ObjectNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ParentAte")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("RegionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegionNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("VillageCouncil")
                        .HasColumnType("integer");

                    b.Property<string>("VillageCouncilName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VillageCouncilNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id", "ChangeDateTime");

                    b.HasIndex("FeatureId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("CadastreFeatureHistoric", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.CadastreFeatureImportEntity", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Ate")
                        .HasColumnType("integer");

                    b.Property<string>("AteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("AteNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CategoryNameShort")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CategoryNameShortBel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("District")
                        .HasColumnType("integer");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DistrictNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("DoUpdate")
                        .HasColumnType("boolean");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ElementNameBel")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer");

                    b.Property<string>("ElementTypeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementTypeNameBel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ElementTypeShortName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ElementTypeShortNameBel")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<int>("IdIae")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ObjectNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ParentAte")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("Region")
                        .HasColumnType("integer");

                    b.Property<string>("RegionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RegionNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortInfo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("VillageCouncil")
                        .HasColumnType("integer");

                    b.Property<string>("VillageCouncilName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VillageCouncilNameBel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("ImportId", "Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("CadastreFeatureImport", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.DossierRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"DossierRecordEntitySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AlternativeDescriptionsBe")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AlternativeDescriptionsRu")
                        .HasColumnType("jsonb");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionBe")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("text");

                    b.Property<int>("LastModifiedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameBeNark")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameBeTarask")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NamingCategoryId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("PossibleNamesBeNark")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("PossibleNamesRu")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("NameBeNark");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameBeNark"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameBeNark"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameBeTarask");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameBeTarask"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameBeTarask"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameRu");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameRu"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameRu"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NamingCategoryId");

                    b.ToTable("DossierRecord", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Vulicy.Domain.DossierRecordHistoricEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("AlternativeDescriptionsBe")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("AlternativeDescriptionsRu")
                        .HasColumnType("jsonb");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionBe")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("text");

                    b.Property<int>("InHistoryById")
                        .HasColumnType("integer");

                    b.Property<int>("LastModifiedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameBeNark")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameBeTarask")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NamingCategoryId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("PossibleNamesBeNark")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("PossibleNamesRu")
                        .HasColumnType("jsonb");

                    b.HasKey("Id", "ChangeDateTime");

                    b.ToTable("DossierRecordHistoric", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.DossierRecordMergeSuggestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeftRecordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RightRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeftRecordId");

                    b.HasIndex("RightRecordId");

                    b.ToTable("DossierRecordMergeSuggestion", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.FeatureEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"FeatureEntitySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DossierRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("ForumRelativeLink")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<string>("HistoricNames")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HistoricPossible")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameBeNark")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameBeTarask")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NamingCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("RenamingReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("YearNamed")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DossierRecordId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("NameBeNark");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameBeNark"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameBeNark"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameBeTarask");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameBeTarask"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameBeTarask"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NameRu");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NameRu"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NameRu"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NamingCategoryId");

                    b.ToTable("Feature", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Vulicy.Domain.FeatureHistoricEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DossierRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("ForumRelativeLink")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<string>("HistoricNames")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HistoricPossible")
                        .HasColumnType("boolean");

                    b.Property<int>("InHistoryById")
                        .HasColumnType("integer");

                    b.Property<int>("LastModifiedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameBeNark")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameBeTarask")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NameRu")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NamingCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("RenamingReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("YearNamed")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id", "ChangeDateTime");

                    b.ToTable("FeatureHistoric", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.ImportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cleared")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Import", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.InitialCadastreFeatureImportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistoricName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HistoricPossible")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCategory")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("YearNamed")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("InitialCadastreFeatureImport", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.NamingCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("NamingCategory", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.OsmFeatureEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<bool>("GeometryUpdatePending")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id", "Type");

                    b.HasIndex("FeatureId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("OsmFeature", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Vulicy.Domain.OsmFeatureHistoricEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id", "Type", "ChangeDateTime");

                    b.HasIndex("FeatureId");

                    b.ToTable("OsmFeatureHistoric", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.OsmFeatureImportEntity", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DoUpdate")
                        .HasColumnType("boolean");

                    b.Property<int?>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ImportId", "Id", "Type");

                    b.HasIndex("FeatureId");

                    b.ToTable("OsmFeatureImport", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Vulicy.Domain.CadastreFeatureEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.FeatureEntity", "Feature")
                        .WithOne("CadastreFeature")
                        .HasForeignKey("Vulicy.Domain.CadastreFeatureEntity", "FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Vulicy.Domain.CadastreFeatureHistoricEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.FeatureEntity", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Vulicy.Domain.CadastreFeatureImportEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.FeatureEntity", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Vulicy.Domain.DossierRecordEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.UserEntity", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vulicy.Domain.NamingCategoryEntity", "NamingCategory")
                        .WithMany()
                        .HasForeignKey("NamingCategoryId");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("NamingCategory");
                });

            modelBuilder.Entity("Vulicy.Domain.DossierRecordMergeSuggestionEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.DossierRecordEntity", "LeftRecord")
                        .WithMany()
                        .HasForeignKey("LeftRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vulicy.Domain.DossierRecordEntity", "RightRecord")
                        .WithMany()
                        .HasForeignKey("RightRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeftRecord");

                    b.Navigation("RightRecord");
                });

            modelBuilder.Entity("Vulicy.Domain.FeatureEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.DossierRecordEntity", "DossierRecord")
                        .WithMany()
                        .HasForeignKey("DossierRecordId");

                    b.HasOne("Vulicy.Domain.UserEntity", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vulicy.Domain.NamingCategoryEntity", "NamingCategory")
                        .WithMany()
                        .HasForeignKey("NamingCategoryId");

                    b.Navigation("DossierRecord");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("NamingCategory");
                });

            modelBuilder.Entity("Vulicy.Domain.OsmFeatureEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.FeatureEntity", "Feature")
                        .WithMany("OsmFeatures")
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Vulicy.Domain.OsmFeatureHistoricEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.FeatureEntity", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Vulicy.Domain.OsmFeatureImportEntity", b =>
                {
                    b.HasOne("Vulicy.Domain.FeatureEntity", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Vulicy.Domain.FeatureEntity", b =>
                {
                    b.Navigation("CadastreFeature");

                    b.Navigation("OsmFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
