@Vulicy.Web_HostAddress = http://localhost:5165

POST {{Vulicy.Web_HostAddress}}/api/import/osm
Content-Type: application/json

"http://127.0.0.1:8080/belarus-251222.osm.pbf"

###

POST {{Vulicy.Web_HostAddress}}/api/import/cadastre
Content-Type: application/json

"http://127.0.0.1:8080/merging/streets_merged.geojson"

###

POST {{Vulicy.Web_HostAddress}}/api/import/cadastre-initial
Content-Type: application/json

"http://127.0.0.1:8080/merging/streets_merged.geojson"

###

POST {{Vulicy.Web_HostAddress}}/api/import/1-initialize-naming-categories

###

POST {{Vulicy.Web_HostAddress}}/api/import/3-initialize-dossier-records

###

POST {{Vulicy.Web_HostAddress}}/api/import/4-create-missing-administrative

###

POST {{Vulicy.Web_HostAddress}}/api/import/5-match-osm-cadastre

###

POST {{Vulicy.Web_HostAddress}}/api/import/6-initialize-features-dossier-categories-references

###

POST {{Vulicy.Web_HostAddress}}/api/import/7-map-fields-from-initial-cadastre-import

###

POST {{Vulicy.Web_HostAddress}}/api/import/8-set-administrative-on-features

###

GET {{Vulicy.Web_HostAddress}}/api/map/naming-categories

###

GET {{Vulicy.Web_HostAddress}}/api/features/search?query=Скарыны

###

GET {{Vulicy.Web_HostAddress}}/api/config

###

GET {{Vulicy.Web_HostAddress}}/api/dossier-records/search?query=Скарына

###

GET {{Vulicy.Web_HostAddress}}/api/dossier-records/22854

###

GET {{Vulicy.Web_HostAddress}}/api/dossier-records/19978/features

###

GET {{Vulicy.Web_HostAddress}}/api/dossier-records/merge-suggestion

###

GET {{Vulicy.Web_HostAddress}}/api/administratives